// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://timefstlnqojqidllokb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpbWVmc3RsbnFvanFpZGxsb2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTM5MTEsImV4cCI6MjA3MDQ4OTkxMX0.PkLLAvSWoK_UaBK5IltQ2hKMCMg1yoXZtSAh65pXXq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});